#!/usr/bin/env python3
"""Publish the public half of a rendered report to the staged share host.

Launch blocker: "Create share link" had nothing behind it. The renderers already
split every report into a local half and a public half, and `deploy_preview.sh`
already knows how to put one report on the host, but it publishes to a fixed
landing path and only understands the comparison report. This is the client that
turns one rendered directory into one shareable URL.

Two rules shape the whole file.

First, the split is an allowlist, not a filter. Only the files named in KINDS
leave the machine. A file that appears in the output directory later, for any
reason, is not published until somebody adds it here on purpose.

Second, the guards run again at publish time, against the bytes about to be
transferred. The renderer's guarantees hold for the file the renderer wrote. The
file on disk an hour later is a different claim: it can be hand-edited, copied
over, or regenerated by an older build. A guard that runs only at render time is
a guard that a hand-edited file walks straight past, so every check here reads
the staged copy, and any failure refuses the whole publish.

Dry run is the default because publishing is outward-facing and irreversible in
the way that matters: once a URL exists, you cannot know who read it.

No credential is read, accepted, printed, or logged here. The transfer rides
`ssh`/`scp` and whatever agent or key the calling shell already has. Nothing in
this file needs a secret, so nothing in this file should ever be given one.

Usage:
  share_publish.py --dir DIR                 # dry run, prints what would be sent
  share_publish.py --dir DIR --confirm       # transfer
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

WEB_ROOT = "/var/www/agilabs-brain-surgery"
# Every share lands under this prefix. The landing page sits at the web root and
# is never a destination here, so no publish can overwrite it.
SHARE_PREFIX = "s"

# The allowlist. `page` is served as index.html inside the share directory so the
# slug URL resolves without a redirect; `summary` is the machine-readable half;
# `extra` is published as named. `local` names the artifacts that must never be
# published and that the skill-name cross-check reads when they are present.
KINDS: dict[str, dict[str, Any]] = {
    "scan": {
        "page": "public-scan.html",
        "summary": "public-scan-summary.json",
        "extra": (),
        "local": ("local-scan.html",),
        "schemas": {"brain-surgery-scan-public/0.1"},
        "check_skill_names": True,
    },
    "comparison": {
        "page": "public-report.html",
        "summary": "public-summary.json",
        "extra": ("social-card.svg",),
        "local": ("local-report.html",),
        "schemas": {"brain-surgery-public/0.4"},
        "check_skill_names": False,
    },
}

# Required fields per declared schema_version, checked before anything is sent.
# The point is not deep validation: it is that a summary whose shape we do not
# recognise is a summary we cannot vouch for, and we publish nothing we cannot
# vouch for.
SCHEMAS: dict[str, dict[str, type | tuple[type, ...]]] = {
    "brain-surgery-scan-public/0.1": {
        # measured false means no transcript was read, and then the dormancy
        # counts are null rather than zero. Null is a shape we publish; zero
        # would be a claim the scan never made.
        "measured": bool,
        "installed": int, "reached": int,
        "dormant": (int, type(None)), "dormant_percent": (int, type(None)),
        "load_attempts": int, "confirmed_loads": int, "failed_loads": int,
        "sessions_analyzed": int, "turns_analyzed": int, "window_days": int,
        "finding_counts": dict, "evaluation_performed": bool,
        "change_status": str, "scan_complete": bool,
    },
    "brain-surgery-public/0.4": {
        "state": str, "tasks": int, "before_passes": int, "after_passes": int,
        "unit": str, "before_total": int, "after_total": int,
        "improved_tasks": int, "unchanged_tasks": int, "regressed_tasks": int,
        "workflows": list, "workflow_count": int, "skills_inspected": int,
        "finding_codes": list, "method_version": str, "model_family": str,
        "change_status": str, "source": str,
    },
}

LOCAL_BLOCK = re.compile(r'id\s*=\s*"local-data"')
PATH_LEAK = re.compile(r"/Users/|/home/")
LOCAL_PAYLOAD = re.compile(r'<script[^>]*id="local-data"[^>]*>(.*?)</script>', re.S)
# argv reaches process listings and shell history. These patterns are the common
# shapes of a pasted secret; the value is never echoed back, only the fact.
SECRET_SHAPED = re.compile(
    r"\b(bearer\s+\S|sk-[A-Za-z0-9]{8}|ghp_[A-Za-z0-9]{8}|xox[baprs]-|AKIA[0-9A-Z]{8})"
    r"|(api[_-]?key|token|secret|password|passwd)\s*[=:]\s*\S", re.I)
SAFE_REMOTE = re.compile(r"^[A-Za-z0-9._@-]+$")
SAFE_PATH = re.compile(r"^/[A-Za-z0-9._/-]+$")


class Refused(Exception):
    """A guard said no. Nothing has been transferred."""


def detect_kind(d: Path) -> str:
    present = [k for k, spec in KINDS.items() if (d / spec["page"]).is_file()]
    if not present:
        raise Refused("%s holds neither %s nor %s, so there is nothing publishable here"
                      % (d, KINDS["scan"]["page"], KINDS["comparison"]["page"]))
    if len(present) > 1:
        # Two reports in one directory means the slug and the index.html would be
        # decided by ordering rather than by intent. Refuse and let the caller
        # point at one report.
        raise Refused("%s holds both a scan report and a comparison report; "
                      "publish them from separate directories" % d)
    return present[0]


def collect(d: Path, kind: str) -> list[tuple[str, str]]:
    """Source file name to published name, in the order they are installed."""
    spec = KINDS[kind]
    wanted = [(spec["page"], "index.html"), (spec["summary"], spec["summary"])]
    wanted += [(n, n) for n in spec["extra"]]
    for src, _ in wanted:
        p = d / src
        if not p.is_file():
            raise Refused("%s is missing from %s; re-render before publishing" % (src, d))
        if p.is_symlink():
            # scp follows symlinks, so a link named like a public artifact would
            # ship whatever it points at, local report included.
            raise Refused("%s is a symlink; refusing to publish what it points at" % p)
    return wanted


def validate_summary(path: Path, kind: str) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise Refused("%s is not readable JSON: %s" % (path, e)) from None
    if not isinstance(data, dict):
        raise Refused("%s does not hold a JSON object" % path)
    declared = data.get("schema_version")
    if declared not in SCHEMAS:
        raise Refused("%s declares schema_version %r, which this publisher does not know"
                      % (path, declared))
    if declared not in KINDS[kind]["schemas"]:
        raise Refused("%s declares schema_version %r, which does not belong to a %s report"
                      % (path, declared, kind))
    for field, typ in SCHEMAS[declared].items():
        if field not in data:
            raise Refused("%s is missing required field %r for %s" % (path, field, declared))
        # bool is an int subclass, so an int field holding True would pass a bare
        # isinstance check and publish a count that is not a count.
        allowed = typ if isinstance(typ, tuple) else (typ,)
        if int in allowed and bool not in allowed and isinstance(data[field], bool):
            raise Refused("%s field %r holds a boolean where %s expects a number"
                          % (path, field, declared))
        if not isinstance(data[field], allowed):
            raise Refused("%s field %r is %s, expected %s"
                          % (path, field, type(data[field]).__name__,
                             " or ".join(t.__name__ for t in allowed)))
    if declared.startswith("brain-surgery-scan-public/"):
        if data["reached"] > data["installed"] or min(data["installed"], data["reached"]) < 0:
            raise Refused("%s reports %d skills reached of %d installed"
                          % (path, data["reached"], data["installed"]))
        # A dormancy count present on an unmeasured scan, or absent on a measured
        # one, means the summary and the page disagree about what was measured.
        nulls = data["dormant"] is None and data["dormant_percent"] is None
        if data["measured"] == nulls:
            raise Refused("%s says measured=%s but carries dormant=%r. Refusing to publish a "
                          "summary that disagrees with itself about what was measured."
                          % (path, data["measured"], data["dormant"]))
    return data


def guard_no_local_block(name: str, text: str) -> None:
    if LOCAL_BLOCK.search(text):
        raise Refused('%s carries an id="local-data" block, which is the local report\'s '
                      "private payload. Refusing to publish." % name)


def guard_no_paths(name: str, text: str) -> None:
    m = PATH_LEAK.search(text)
    if m:
        line = text.count("\n", 0, m.start()) + 1
        raise Refused("%s carries a filesystem path (%r at line %d). Refusing to publish."
                      % (name, m.group(0), line))


def local_skill_names(d: Path, kind: str) -> set[str] | None:
    """Skill names the local artifact knows about, or None when it is absent.

    Cross-checking the public HTML against the names in the local artifact is the
    strongest test available: it does not guess what a skill name looks like, it
    asks this machine which names exist and then proves none of them left.
    """
    if not KINDS[kind]["check_skill_names"]:
        return None
    for fname in KINDS[kind]["local"]:
        p = d / fname
        if not p.is_file():
            continue
        m = LOCAL_PAYLOAD.search(p.read_text(encoding="utf-8"))
        if not m:
            raise Refused("%s has no local-data payload to cross-check names against. "
                          "Re-render, or move the local artifact out of the directory." % p)
        try:
            raw = json.loads(html.unescape(m.group(1)))
        except ValueError as e:
            raise Refused("%s holds a local-data payload that will not parse (%s), so the "
                          "skill-name check cannot run." % (p, e)) from None
        names: set[str] = set()
        for f in raw.get("findings", []):
            if f.get("skill"):
                names.add(str(f["skill"]))
            for n in (f.get("evidence") or {}).get("names", []) or []:
                names.add(str(n))
        for u in raw.get("most_used", []):
            if u.get("skill"):
                names.add(str(u["skill"]))
        return names
    return None


def guard_no_skill_names(name: str, text: str, names: set[str]) -> None:
    for skill in sorted(names):
        # Very short names collide with ordinary prose and would refuse every
        # publish, which is how a guard gets switched off.
        if len(skill) < 3:
            continue
        m = re.search(r"(?<![A-Za-z0-9])%s(?![A-Za-z0-9])" % re.escape(skill), text, re.I)
        if m:
            around = text[max(0, m.start() - 40):m.end() + 40].replace("\n", " ")
            raise Refused("%s names the skill %r (near: ...%s...). Skill names stay on the "
                          "scanned machine. Refusing to publish." % (name, skill, around))


def run_guards(d: Path, kind: str, files: list[tuple[str, str]]) -> list[str]:
    """Every guard, against the files about to leave. Returns what was checked."""
    summary_name = KINDS[kind]["summary"]
    validate_summary(d / summary_name, kind)
    names = local_skill_names(d, kind)
    for src, _ in files:
        text = (d / src).read_text(encoding="utf-8", errors="replace")
        guard_no_local_block(src, text)
        guard_no_paths(src, text)
        if names:
            guard_no_skill_names(src, text, names)
    checked = [
        "summary schema: %s validated against its declared schema_version" % summary_name,
        "allowlist: only %s" % ", ".join(s for s, _ in files),
        'no id="local-data" block in any published file',
        "no /Users/ or /home/ path in any published file",
    ]
    if names is None:
        checked.append("skill names: not applicable to a %s report" % kind
                       if not KINDS[kind]["check_skill_names"]
                       else "skill names: skipped, no local artifact in the directory")
    else:
        checked.append("skill names: %d name(s) from the local artifact, none present" % len(names))
    return checked


def slug_for(summary: Path) -> str:
    """Short content hash. Same summary, same URL; new scan, new URL."""
    return hashlib.sha256(summary.read_bytes()).hexdigest()[:10]


def transfer(d: Path, files: list[tuple[str, str]], remote: str, web_root: str, slug: str) -> None:
    dest = "%s/%s/%s" % (web_root, SHARE_PREFIX, slug)
    staged = "/tmp/brain-surgery-%s" % slug
    with tempfile.TemporaryDirectory() as tmp:
        stage = Path(tmp)
        for src, published in files:
            (stage / published).write_bytes((d / src).read_bytes())
        # Staged idiom: land in /tmp as the login
        # user, then install into the web root as root. A per-slug staging
        # directory keeps two concurrent publishes from reading each other's files.
        subprocess.run(["ssh", remote, "mkdir -p %s" % staged], check=True)
        subprocess.run(["scp", "-q"] + [str(stage / p) for _, p in files]
                       + ["%s:%s/" % (remote, staged)], check=True)
        names = " ".join("%s/%s" % (staged, p) for _, p in files)
        subprocess.run(["ssh", remote,
                        "sudo install -d -m 755 -o root -g root %s "
                        "&& sudo install -m 644 -o root -g root %s %s/ "
                        "&& rm -rf %s && ls -la %s/" % (dest, names, dest, staged, dest)],
                       check=True)


def main() -> int:
    if any(SECRET_SHAPED.search(a) for a in sys.argv[1:]):
        # Printed without the value: repeating it here would put it in the log we
        # are refusing it to keep out of.
        sys.stderr.write("Refusing to run: an argument looks like a credential. This script "
                         "never needs one. Remove it and re-run.\n")
        return 2

    p = argparse.ArgumentParser(description="Publish the public artifacts of a rendered report.")
    p.add_argument("--dir", required=True, type=Path, help="rendered output directory")
    p.add_argument("--remote", default="report-host", help="ssh host alias for the report service")
    p.add_argument("--web-root", default=WEB_ROOT, help="web root on the remote (default: %s)" % WEB_ROOT)
    p.add_argument("--confirm", action="store_true",
                   help="actually transfer. Without this the run is a dry run.")
    a = p.parse_args()

    try:
        if not a.dir.is_dir():
            raise Refused("%s is not a directory" % a.dir)
        if not SAFE_REMOTE.match(a.remote):
            raise Refused("remote %r is not a plain host alias" % a.remote)
        if not SAFE_PATH.match(a.web_root):
            raise Refused("web root %r is not a plain absolute path" % a.web_root)

        kind = detect_kind(a.dir)
        files = collect(a.dir, kind)
        checked = run_guards(a.dir, kind, files)
        slug = slug_for(a.dir / KINDS[kind]["summary"])
    except Refused as e:
        sys.stderr.write("REFUSED: %s\n" % e)
        return 1
    except OSError as e:
        sys.stderr.write("Failed to read the rendered directory: %s\n" % e)
        return 2

    dest = "%s/%s/%s" % (a.web_root, SHARE_PREFIX, slug)
    print("Report kind:  %s" % kind)
    print("Source:       %s" % a.dir)
    print("Remote:       %s" % a.remote)
    print("Destination:  %s/" % dest)
    print("Share path:   /%s/%s/" % (SHARE_PREFIX, slug))
    print("\nGuards passed:")
    for line in checked:
        print("  ok  %s" % line)
    print("\nWould send %d file(s):" % len(files))
    for src, published in files:
        print("  %-24s -> %s/%s  (%d bytes)"
              % (src, dest, published, (a.dir / src).stat().st_size))
    held = sorted(q.name for q in a.dir.iterdir()
                  if q.is_file() and q.name not in {s for s, _ in files})
    if held:
        print("\nNot published (not on the allowlist):")
        for n in held:
            print("  %s" % n)

    if not a.confirm:
        print("\nDRY RUN. Nothing was transferred. Re-run with --confirm to publish.")
        return 0

    try:
        transfer(a.dir, files, a.remote, a.web_root, slug)
    except subprocess.CalledProcessError as e:
        sys.stderr.write("Transfer failed (%s exited %d). The share may be incomplete.\n"
                         % (e.cmd[0], e.returncode))
        return 2
    print("\nPublished. Share path: /%s/%s/" % (SHARE_PREFIX, slug))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
